# Generated by Django 3.2.5 on 2021-08-06 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_profilejson'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boolean', models.CharField(choices=[{'OK', 'NG'}], max_length=100)),
            ],
        ),
    ]
