# Generated by Django 3.2.5 on 2021-08-06 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_choicemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChoiceModel',
        ),
    ]
