# Generated by Django 3.2.5 on 2021-09-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0004_auto_20210909_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Adress'},
        ),
        migrations.AddField(
            model_name='book',
            name='publish_countires',
            field=models.ManyToManyField(to='book_outlet.Country'),
        ),
    ]
